image: 'gradle:6.6.1-jdk8'

cache:
  key: '$CI_COMMIT_BRANCH'
  paths:
    - .gradle
    - .gradlehome
  when: always

stages:
  - build_publish
  - docs

snapshot:
  stage: build_publish
  script:
    - 'gradle shadowJar -g .gradlehome'
    - 'gradle publish -g .gradlehome'
  artifacts:
    paths:
      - ulib-*/build/libs/*.jar
  only:
    - develop

release:
  stage: build_publish
  script:
    - 'gradle shadowJar -g .gradlehome -Prelease'
    - 'gradle publish -g .gradlehome -Prelease'
  artifacts:
    paths:
      - ulib-*/build/libs/*.jar
  only:
    - web
  except:
    - develop

pages:
  stage: docs
  script:
    - 'gradle javadoc -g .gradlehome -Prelease'
    - 'mkdir public'
    - 'cd public'
    - 'cp -r ../docs ./'
    - 'cd docs'
    - 'mv ../../ulib-core-api/build/docs/javadoc core'
    - 'mv ../../ulib-spigot-api/build/docs/javadoc spigot'
    - 'mv ../../ulib-bungeecord-api/build/docs/javadoc bungeecord'
  artifacts:
    paths:
      - public
  only:
    - web
  except:
    - develop
