image: 'gradle:7.3.1-jdk17'

variables:
  GRADLE_EXEC: 'gradle -g .gradlehome'

cache:
  key: '$CI_COMMIT_BRANCH'
  paths:
    - .gradle
    - .gradlehome
  when: always

stages:
  #- test
  - build # ready-for-use files
  - publish # api files for maven repository
  - docs # javadocs

# snapshots
snapshot build:
  stage: build
  script: "$GRADLE_EXEC build -Pvariation=snapshot"
  artifacts: &artifacts_build
    paths:
      - loader/build/libs/ulib-loader-*.jar
  # only run if this is a snapshot, triggered via the web
  rules: &rules_snapshot
    - if: $FULL_RELEASE != null  # cancel if release
      when: never
    - if: $CI_PIPELINE_SOURCE == 'web' # only via web
      changes: &file_changes
        - "*.gradle"
        - "*-api/**/*"
        - "*-impl/**/*"
        - "loader/**/*"
        - "docs/**/*"
        - "gradle/**/*"
snapshot publication:
  stage: publish
  script: "$GRADLE_EXEC publish -Pvariation=snapshot"
  artifacts: &artifacts_publication
    paths:
      - "*-api/build/libs/*.jar"
  rules: *rules_snapshot

# releases
release build:
  stage: build
  script: "$GRADLE_EXEC build -Pvariation=release"
  artifacts: *artifacts_build
  # only run if this is a full release, triggered via the web
  rules: &rules_release
    - if: $CI_PIPELINE_SOURCE != 'web' # cancel if not web
      when: never
    - if: $FULL_RELEASE != null  # only on full release
      changes: *file_changes
release publication:
  stage: publish
  script: "$GRADLE_EXEC publish -Pvariation=release"
  artifacts: *artifacts_publication
  rules: *rules_release
pages:
  stage: docs
  script: '$GRADLE_EXEC docsWebpage -Pvariation=release'
  artifacts:
    paths:
      - public
  rules: *rules_release