image: 'gradle:6.6.1-jdk8'

cache:
  key: '$CI_COMMIT_BRANCH'
  paths:
    - .gradle
    - .gradlehome
  when: always

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - 'gradle shadowJar -g .gradlehome'
  artifacts:
    paths:
      - ulib-*/build/libs/*.jar
  only:
    - master
    - web

repo:
  stage: deploy
  script:
    - 'gradle publish -g .gradlehome'
  only:
    - master

pages:
  stage: deploy
  script:
    - 'gradle javadoc -g .gradlehome'
    - 'mkdir public'
    - 'cd public'
    - 'cp -r ../docs ./'
    - 'cd docs'
    - 'mv ../../ulib-core-api/build/docs/javadoc core'
    - 'mv ../../ulib-spigot-api/build/docs/javadoc spigot'
    - 'mv ../../ulib-bungeecord-api/build/docs/javadoc bungeecord'
  artifacts:
    paths:
      - public
  only:
    - master
