image: 'gradle:7.3.1-jdk17'

variables:
  GRADLE_EXEC: 'gradle -g .gradlehome'

cache:
  key: '$CI_COMMIT_BRANCH'
  paths:
    - .gradle
    - .gradlehome
  when: always

stages:
  - build # ready-for-use files
  - test # test that stuff!
  - publish # api files for maven repository

test:
  stage: test
  script: "$GRADLE_EXEC test"
  # only run if this is triggered via the web
  rules:
    - if: $CI_PIPELINE_SOURCE == 'web' # only via web

# snapshots
snapshot build:
  stage: build
  script: "$GRADLE_EXEC build -Pvariation=snapshot"
  artifacts: &artifacts
    paths:
      - loader/build/libs/ulib-loader-*.jar
      - core/build/libs/*jar
      - minecraft/build/libs/*jar
      - spigot/build/libs/*jar
      - velocity/build/libs/*jar
      - bungeecord/build/libs/*jar
  # only run if this is a snapshot, triggered via the web
  rules: &rules_snapshot
    - if: $FULL_RELEASE != null  # cancel if release
      when: never
    - if: $CI_PIPELINE_SOURCE == 'web' # only via web
snapshot publication:
  stage: publish
  script: "$GRADLE_EXEC publish -Pvariation=snapshot"
  artifacts: *artifacts
  rules: *rules_snapshot

# releases
release build:
  stage: build
  script: "$GRADLE_EXEC build -Pvariation=release"
  artifacts: *artifacts
  # only run if this is a full release, triggered via the web
  rules: &rules_release
    - if: $CI_PIPELINE_SOURCE != 'web' # cancel if not web
      when: never
    - if: $FULL_RELEASE != null  # only on full release
release publication:
  stage: publish
  script: "$GRADLE_EXEC publish -Pvariation=release"
  artifacts: *artifacts
  rules: *rules_release