image: 'gradle:6.6.1-jdk8'

cache:
  key: '$CI_COMMIT_BRANCH'
  paths:
    - .gradle
    - .gradlehome
  when: always

stages:
  - build_publish
  - docs

snapshot:
  stage: build_publish
  script:
    - 'gradle shadowJar publish -g .gradlehome'
  artifacts: &artifacts
    paths:
      # core
      - ulib-core/build/libs/*-lib.jar
      - ulib-core-api/build/libs/*-javadoc.jar
      - ulib-core-api/build/libs/*-sources.jar
      # spigot
      - ulib-spigot/build/libs/*-plugin.jar
      - ulib-spigot-api/build/libs/*-javadoc.jar
      - ulib-spigot-api/build/libs/*-sources.jar
      # bungeecord
      - ulib-bungeecord/build/libs/*-plugin.jar
      - ulib-bungeecord-api/build/libs/*-javadoc.jar
      - ulib-bungeecord-api/build/libs/*-sources.jar
      # velocity
      - ulib-velocity/build/libs/*-plugin.jar
      - ulib-velocity-api/build/libs/*-javadoc.jar
      - ulib-velocity-api/build/libs/*-sources.jar
  only:
    - develop

release:
  stage: build_publish
  script:
    - 'gradle shadowJar publish -g .gradlehome -Prelease'
  artifacts: *artifacts
  only:
    - web
  except:
    - develop

pages:
  stage: docs
  script:
    - 'gradle javadoc -g .gradlehome -Prelease'
    - 'mkdir public'
    - 'cd public'
    - 'cp -r ../docs ./'
    - 'cd docs'
    - 'mv ../../ulib-core-api/build/docs/javadoc core'
    - 'mv ../../ulib-spigot-api/build/docs/javadoc spigot'
    - 'mv ../../ulib-bungeecord-api/build/docs/javadoc bungeecord'
    - 'mv ../../ulib-velocity-api/build/docs/javadoc velocity'
  artifacts:
    paths:
      - public
  only:
    - web
  except:
    - develop
