# uLib configuration file.

# Internal setting to track config version updates.
# !!! DO NOT CHANGE !!!
config-version: 3

# The ulib-data-directory is uLib's main directory for all its files.
# This directory can only be changed via command-line options.
# To change it, add this to the command-line (before the -jar):
#   -Dulib.directory.main=YOUR_VALUE
# Defaults to '.ulib'

# Switch to override properties set via the command line.
# Usually the properties set via command line override the settings in this file.
# Possible values: true, false; Default value: false
override-command-line: false

# Switch to force uLib to handle all requests synchronously that would usually worked off multi-threaded.
# Enforcing synchronous work will significantly decrease uLib's performance in certain areas!
# Possible values: true, false; Default: false
# Command line equivalent: -Dulib.forcesync=YOUR_VALUE
force-synchronous-work: false

# Switch to allow uLib to use potentially unsafe operations if necessary.
# Allowing unsafe operations is potentially dangerous and can lead to instability and/or damage of any kind!
# Use this at your own risk!
# Possible values: allow, deny; Default: deny
# Command line equivalent: -Dulib.unsafe_operations=YOUR_VALUE
unsafe-operations: deny

# Directories settings
directories:
  # Where the log files will be placed.
  # If the value is '' the 'logs' directory will be placed inside the ulib-data-directory.
  # Default: ''
  # Command line equivalent: -Dulib.directory.logs=YOUR_VALUE
  logs: ''

  # Where cached files will be placed.
  # If the value is '' the 'cache' directory will be placed inside the ulib-data-directory.
  # Default: ''
  # Command line equivalent: -Dulib.directory.cache=YOUR_VALUE
  cache: ''

  # Where fully-resolved maven artifacts will be stored.
  # If the value is '' the 'libraries' directory will be placed inside the ulib-data-directory.
  # Default: ''
  # Command line equivalent: -Dulib.directory.libraries=YOUR_VALUE
  libraries: ''
